import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv(r"C:\Users\SAFIYA BANU\Downloads\dirty_cafe_sales.csv")
#data exploration
print("\nFirst 5 rows\n")
print(df.head())
print("\nInformation about dataset\n")
print(df.info())
print("\nDescription of data\n")
print(df.describe())
print("\nShape\n")
print(df.shape)
print("\nColumn",df.columns)
#Finding missing values
print("\nMissing values\n")
print(df.isnull().sum())
#finding duplicate values
print("\nDuplicate rows\n")
print(df.duplicated().sum())
#replace invalid vales
df.replace("ERROR",np.nan,inplace=True)
df.replace("UNKNOWN",np.nan,inplace=True)
#convert the values
df["Quantity"]=pd.to_numeric(df["Quantity"],errors="coerce")
df["Price Per Unit"]=pd.to_numeric(df["Price Per Unit"],errors="coerce")
df["Total Spent"]=pd.to_numeric(df["Total Spent"],errors="coerce")
df["Transaction Date"]=pd.to_datetime(df["Transaction Date"],errors="coerce")
print("\nUpdated dataset information\n")
print(df.info())
print("\nMissing values after cleaning\n")
print(df.isnull().sum())
df["Location"]=df["Location"].fillna("Unknown")
df["Payment Method"]=df["Payment Method"].fillna("Unknown")
df["Total Spent"]=df["Total Spent"].fillna(df["Quantity"]*df["Price Per Unit"])
df.dropna(subset=["Item","Quantity","Price Per Unit","Transaction Date"],inplace=True)
print(df.shape)
print(df.isnull().sum())
#Top Selling Items
item_counts=df["Item"].value_counts()
plt.figure(figsize=(8,5))
plt.bar(item_counts.index,item_counts.values)
plt.title("Top Selling Cafe Items")
plt.xlabel("Items")
plt.ylabel("Number of Transactions")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("top_selling_items.png")
plt.show()
#Customer Purchased Location
locations=df[df["Location"]!="Unknown"]["Location"].value_counts()
plt.figure(figsize=(8,5))
plt.bar(locations.index,locations.values)
plt.title("Customer Purchased Location")
plt.xlabel("Locations")
plt.ylabel("Number of Transactions")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("customer_purchased_location.png")
plt.show()
#Payment method
plt.figure(figsize=(6,5))
payment=df[df["Payment Method"]!="Unknown"]["Payment Method"].value_counts()
plt.pie(payment.values,startangle=90,labels=payment.index,autopct='%1.1f%%')
plt.title("Payment Method Distribution")
plt.savefig("payment_method")
plt.show()
#Trends over Time
monthly_sales=df.groupby(df["Transaction Date"].dt.month)["Total Spent"].sum()
plt.figure(figsize=(8,5))
plt.plot(monthly_sales.index,monthly_sales.values,marker="o")
plt.title("Monthly Sales Trends")
plt.xlabel("Months")
plt.ylabel("Total sales")
plt.xticks(range(1,13))
plt.grid(True)
plt.savefig("Trends_over_time.png")
plt.show()
#Distribution of Total Spent
plt.figure(figsize=(8,5))
plt.boxplot(df["Total Spent"])
plt.title("Distribution of Total Spent")
plt.ylabel("Total Spent")
plt.savefig("distribution_of_total_spent.png")
plt.show()
#Revenue by Item
revenue=df.groupby("Item")["Total Spent"].sum()
plt.figure(figsize=(8,5))
plt.bar(revenue.index,revenue.values)
plt.title("Revenue by Item")
plt.xlabel("Item")
plt.ylabel("Total Revenue")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("revenue_by_item.png")
plt.show()
#Correlation Heatmap
corr=df.corr(numeric_only=True)
print(corr)
plt.figure(figsize=(6,5))
plt.imshow(corr,cmap="coolwarm")
plt.xticks(range(len(corr.columns)),corr.columns,rotation=0)
plt.yticks(range(len(corr.columns)),corr.columns)
plt.colorbar()
plt.title("Correlation Heatmap")
plt.tight_layout()
plt.savefig("correlation_heatmap.png")
plt.show()
#save cleaned dataset
df.to_csv("cleaned_cafe_sales.csv",index=False)




